replicaCount: 1
image:
  repository: ghcr.io/shareify-project/shareify-booking-service
  pullPolicy: Always
  tag: "2a3346a"
imagePullSecrets:
  - name: ghcr-secret
env:
  databaseUrl: "postgresql://postgres:shareify-secure-db-pass@postgres-db:5432/booking_service"
service:
  type: ClusterIP
  port: 8000
persistence:
  enabled: true
  storageClass: "nfs-client"
  size: 1Gi
  mountPath: /app/data
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 16Mi

config: {}
secrets: {}








